[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_d_app = "SomeHashMpGXkYsWTK6W2BkgFidsLeZ7F476zPEfcYn"

[programs.devnet]
solana_d_app = "SomeHashMpGXkYsWTK6W2BkgFidsLeZ7F476zPEfcYn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/shohihara/.config/solana/id.json" # YOUR_USERNAMEは自分のPCのユーザー名に置き換えてください


[scripts]
test = "yarn run mocha -t 1000000 tests/"
