[features]
seeds = false
skip-lint = false

[programs.localnet]
myepicproject = ""

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "fooKey.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
