[features]
seeds = false
skip-lint = false

[programs.localnet]
myepicproject = "7ddmBbZfTMKwL7i4HwDBRifrrftxN5YFj5CmmzoXdATw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "target/deploy/myepicproject-keypair.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
